import { ArrowUpRight, FileText, MessageSquare, Plus, Sparkles } from "lucide-react";
import { getCurrentUser } from "@/lib/auth";
import { getDashboardStats, getWorkspaceForUser } from "@/lib/db";

export default async function DashboardPage() {
  const user = (await getCurrentUser())!;
  const stats = getDashboardStats(user.id);
  const workspace = getWorkspaceForUser(user.id);
  return <main className="dashboard"><div className="greeting"><div><div className="eyebrow">{workspace?.name ?? "Your workspace"}</div><h1>Good morning, {user.name.split(" ")[0]}.</h1><p>Your thinking space is ready when you are.</p></div><a className="quick-action" href="/assistant"><Plus size={16} /> Start a conversation</a></div><section className="stat-grid"><StatCard label="AI conversations" value={stats.counts.conversations.toString()} icon={<MessageSquare size={17} />} /><StatCard label="Files in workspace" value={stats.counts.files.toString()} icon={<FileText size={17} />} color="coral" /><StatCard label="Active projects" value={stats.counts.projects.toString()} icon={<Sparkles size={17} />} color="sun" /><StatCard label="AI credits used" value={`${stats.counts.aiCreditsUsed}%`} icon={<ArrowUpRight size={17} />} /></section><div className="content-grid"><section className="panel"><div className="panel-header"><h2>Recent conversations</h2><a className="text-button" href="/assistant">View all <ArrowUpRight size={13} /></a></div>{stats.conversations.length ? <div className="activity">{stats.conversations.map((conversation) => <div className="activity-row" key={conversation.id}><div className="activity-dot" /><div><p>{conversation.title}</p><small>Updated recently</small></div></div>)}</div> : <EmptyState icon={<MessageSquare size={19} />} title="Your conversations will live here" text="Start a conversation with Aether to explore an idea, solve a problem, or move work forward." />}</section><section className="panel"><div className="panel-header"><h2>Workspace pulse</h2><span className="eyebrow">This week</span></div><div className="activity"><div className="activity-row"><div className="activity-dot" /><div><p>Workspace created</p><small>Your new space is ready for work.</small></div></div><div className="activity-row"><div className="activity-dot" style={{ background: "var(--teal)" }} /><div><p>AI assistant is ready</p><small>Connect an OpenRouter key to begin.</small></div></div></div></section></div></main>;
}

function StatCard({ label, value, icon, color = "" }: { label: string; value: string; icon: React.ReactNode; color?: string }) { return <div className={`stat-card ${color}`}><span className="stat-label">{label}</span><span className="stat-value">{value}</span><span style={{ position: "absolute", right: 18, top: 19, color: "var(--teal)" }}>{icon}</span></div>; }
function EmptyState({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="empty-state"><div><div className="empty-icon">{icon}</div><strong>{title}</strong><p>{text}</p></div></div>; }