"use client";

import { FormEvent, useEffect, useState } from "react";
import { Copy, Heart, LoaderCircle, Mail, Save, Search, Settings2, Trash2, Users } from "lucide-react";

type Prompt = { id: string; title: string; content: string; category: string; favorite: number };

export function PromptsWorkspace() {
  const [prompts, setPrompts] = useState<Prompt[]>([]); const [selected, setSelected] = useState<Prompt | null>(null); const [search, setSearch] = useState(""); const [showForm, setShowForm] = useState(false); const [error, setError] = useState("");
  async function load(term = search) { const response = await fetch(`/api/prompts?search=${encodeURIComponent(term)}`); const result = await response.json() as { prompts?: Prompt[]; error?: string }; if (!response.ok) setError(result.error ?? "Unable to load prompts."); else { setPrompts(result.prompts ?? []); if (!selected && result.prompts?.[0]) setSelected(result.prompts[0]); } }
  useEffect(() => { void load(); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch("/api/prompts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const result = await response.json() as { prompt?: Prompt; error?: string }; if (!response.ok || !result.prompt) setError(result.error ?? "Unable to save prompt."); else { setPrompts((current) => [result.prompt!, ...current]); setSelected(result.prompt); setShowForm(false); } }
  async function remove() { if (!selected || !window.confirm("Delete this prompt?")) return; await fetch(`/api/prompts/${selected.id}`, { method: "DELETE" }); const remaining = prompts.filter((prompt) => prompt.id !== selected.id); setPrompts(remaining); setSelected(remaining[0] ?? null); }
  async function favorite() { if (!selected) return; const response = await fetch(`/api/prompts/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...selected, favorite: !selected.favorite }) }); const result = await response.json() as { prompt: Prompt }; setSelected(result.prompt); setPrompts((current) => current.map((prompt) => prompt.id === result.prompt.id ? result.prompt : prompt)); }
  return <main className="utility-page"><aside className="utility-sidebar"><div className="utility-head"><div><div className="eyebrow">Workspace</div><h1>Prompt library</h1></div><button className="quick-action compact" onClick={() => setShowForm(true)}>New prompt</button></div><label className="utility-search"><Search size={15} /><input value={search} onChange={(event) => { setSearch(event.target.value); void load(event.target.value); }} placeholder="Search prompts" /></label><div className="utility-list">{prompts.map((prompt) => <button className={selected?.id === prompt.id ? "selected" : ""} key={prompt.id} onClick={() => setSelected(prompt)}><strong>{prompt.title}</strong><small>{prompt.category}</small></button>)}{!prompts.length && <div className="utility-empty">No prompts yet.</div>}</div></aside><section className="utility-detail">{showForm ? <form className="utility-form" onSubmit={save}><div className="eyebrow">Prompt library</div><h2>Create a reusable prompt.</h2><label className="field"><span>Title</span><input name="title" required placeholder="Explain a concept clearly" /></label><label className="field"><span>Category</span><input name="category" defaultValue="General" /></label><label className="field"><span>Prompt</span><textarea name="content" required rows={10} placeholder="Explain {{topic}} for a {{audience}}..." /></label><div className="utility-actions"><button type="button" className="text-button" onClick={() => setShowForm(false)}>Cancel</button><button className="quick-action compact">Save prompt</button></div></form> : selected ? <div className="prompt-detail"><header><div><div className="eyebrow">{selected.category}</div><h2>{selected.title}</h2></div><div><button className="icon-button" onClick={() => void favorite()} aria-label="Favorite prompt"><Heart size={16} fill={selected.favorite ? "currentColor" : "none"} /></button><button className="icon-button" onClick={() => navigator.clipboard.writeText(selected.content)} aria-label="Copy prompt"><Copy size={16} /></button><button className="icon-button" onClick={() => void remove()} aria-label="Delete prompt"><Trash2 size={16} /></button></div></header><pre>{selected.content}</pre><p>Use variable tokens such as &#123;&#123;topic&#125;&#125; when you want to fill in context before copying it into a conversation.</p></div> : <div className="utility-empty-large">Create a prompt to give your best workflows a reusable home.</div>}{error && <div className="form-error">{error}</div>}</section></main>;
}

type TeamResult = { members: { id: string; name: string; email: string; role: string }[]; invitations: { id: string; email: string; role: string; status: string }[] };
export function TeamWorkspace() { const [data, setData] = useState<TeamResult>({ members: [], invitations: [] }); const [email, setEmail] = useState(""); const [error, setError] = useState(""); async function load() { const response = await fetch("/api/team"); const result = await response.json() as TeamResult; setData(result); } useEffect(() => { void load(); }, []); async function invite(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/team", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const result = await response.json() as { error?: string }; if (!response.ok) setError(result.error ?? "Unable to create invitation."); else { setEmail(""); setError(""); await load(); } } return <main className="utility-page single"><section className="utility-detail team-detail"><div className="eyebrow">Workspace</div><h1>Team</h1><p className="utility-lead">Manage who can access this workspace and keep invitations visible.</p><form className="invite-form" onSubmit={invite}><Mail size={16} /><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required placeholder="colleague@company.com" /><button className="quick-action compact">Invite member</button></form>{error && <div className="form-error">{error}</div>}<section className="panel utility-panel"><div className="panel-header"><h2><Users size={16} /> Members</h2><span>{data.members.length}</span></div>{data.members.map((member) => <div className="utility-row" key={member.id}><span className="avatar">{member.name.slice(0, 2).toUpperCase()}</span><div><strong>{member.name}</strong><small>{member.email}</small></div><em>{member.role}</em></div>)}</section><section className="panel utility-panel"><div className="panel-header"><h2>Pending invitations</h2><span>{data.invitations.length}</span></div>{data.invitations.map((invitation) => <div className="utility-row" key={invitation.id}><Mail size={16} /><div><strong>{invitation.email}</strong><small>{invitation.status}</small></div><em>{invitation.role}</em></div>)}{!data.invitations.length && <div className="utility-empty">No pending invitations.</div>}</section></section></main>; }

export function SettingsWorkspace({ user }: { user: { name: string; email: string; role: string } }) { const [name, setName] = useState(user.name); const [saved, setSaved] = useState(false); const [error, setError] = useState(""); async function save(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/settings/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const result = await response.json() as { error?: string }; if (!response.ok) setError(result.error ?? "Unable to save profile."); else setSaved(true); } return <main className="utility-page single"><section className="utility-detail settings-detail"><div className="eyebrow">Account</div><h1><Settings2 size={25} /> Settings</h1><p className="utility-lead">Manage your profile and account preferences.</p><form className="utility-form" onSubmit={save}><label className="field"><span>Display name</span><input value={name} onChange={(event) => { setName(event.target.value); setSaved(false); }} required /></label><label className="field"><span>Email</span><input value={user.email} disabled /></label><label className="field"><span>Role</span><input value={user.role} disabled /></label>{error && <div className="form-error">{error}</div>}<button className="quick-action compact"><Save size={15} /> {saved ? "Saved" : "Save profile"}</button></form></section></main>; }